# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '2b358d85-c419-4732-b382-f68ef1526f84'
  imageRepository: 'party'
  containerRegistry: 'partytimecontainerregistry.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Test
  displayName: Test the application
  jobs:
  - job: Testing
    displayName: Dependency checking and publishing results
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: dependency-check-build-task@6
      inputs:
        projectName: 'Partytime.Party'
        scanPath: '**/*.csproj'
        format: 'HTML, JSON, JUNIT'
        failOnCVSS: '8'
        enableExperimental: true
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'dependency-check\*junit.xml'
        searchFolder: '$(Common.TestResultsDirectory)'
        testRunTitle: 'Dependency Check'
  - job: Security
    displayName: Check for security flaws
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: MicrosoftSecurityDevOps@1
    displayName: 'Microsoft Security DevOps'
    
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest
          $(Build.BuildId)
